import React, { useState } from 'react';
import { FaChevronDown, FaChevronUp, FaArrowLeft } from 'react-icons/fa';
import { useNavigate } from 'react-router-dom';
import './MarketingTerms.css';

const MarketingRules = () => {
    const navigate = useNavigate();
    const [openSection, setOpenSection] = useState(null);

    const toggleSection = (section) => {
        setOpenSection(openSection === section ? null : section);
    };

    const sections = [
        {
            id: 1,
            title: "1. Property Verification Rule",
            content: `Client must submit:
• Ownership proof
• RERA / legal approvals
• Government ID
• Authorized signatory details (for developers)

Bada Builder will not promote any illegal or disputed property.`
        },
        {
            id: 2,
            title: "2. Pricing Honesty Rule",
            content: `Client must declare true and final property price.

Any under-reporting, manipulation, or hidden deals will:
• Cancel the agreement
• Forfeit all paid amounts
• Blacklist the client from future services`
        },
        {
            id: 3,
            title: "3. Exclusive Rights Rule (Packages 5 & 6)",
            content: `Developers must:
• Give exclusive selling rights
• Not appoint any other broker
• Not self-sell during the contract

Violation = Immediate termination + full brokerage penalty`
        },
        {
            id: 4,
            title: "4. Payment Discipline Rule",
            content: `All payments must be made within the agreed timeline.

Late payment penalty:
2% per month on pending amount.`
        },
        {
            id: 5,
            title: "5. Content Usage Rule",
            content: `All marketing content:
• Belongs to Bada Builder
• Cannot be reused, edited, or sold
• Cannot be posted without credit or watermark`
        },
        {
            id: 6,
            title: "6. Lead Handling Rule",
            content: `Leads generated by Bada Builder:
• Must be handled only through Bada Builder
• Cannot be diverted to third parties

Violation = Full brokerage + legal action`
        },
        {
            id: 7,
            title: "7. On-Site Cooperation Rule",
            content: `Client must:
• Provide property access
• Maintain cleanliness
• Ensure shoot permissions
• Assign a contact person

Delay due to client negligence will not be Bada Builder's responsibility.`
        },
        {
            id: 8,
            title: "8. Advertisement Approval Rule",
            content: `Client must approve creatives within 48 hours.

No response = auto-approval.`
        },
        {
            id: 9,
            title: "9. Influencer & Ad Budget Rule",
            content: `Influencer fees & ad spends are:
• Non-refundable
• Separate from brokerage`
        },
        {
            id: 10,
            title: "10. RISG Compliance Rule (Package 6)",
            content: `Developer must:
• Provide rent-ready property
• Share possession timeline
• Maintain property condition

Failure = RISG cancellation.`
        },
        {
            id: 11,
            title: "11. Confidentiality Rule",
            content: `All business data, leads, creatives, pricing models, and strategies are confidential.`
        },
        {
            id: 12,
            title: "12. Termination Rule",
            content: `Bada Builder may terminate the contract if:
• Fraud is detected
• Payments are delayed
• Legal disputes arise
• Property becomes non-compliant`
        },
        {
            id: 13,
            title: "13. Legal Authority",
            content: `Bada Builder reserves the right to:
• Refuse service
• Modify packages
• Update rules anytime`
        }
    ];

    return (
        <div className="marketing-terms-page">
            <div className="terms-header">
                <button className="back-btn" onClick={() => navigate('/services/marketing')}>
                    <FaArrowLeft /> Back
                </button>
                <h1>Rules & Regulations</h1>
                <p className="terms-subtitle">Marketing, Sole Selling, Influencer & RISG Services</p>
            </div>

            <div className="terms-intro">
                <p>
                    These Rules & Regulations apply to all clients using <strong>Bada Builder's</strong> marketing, 
                    sole selling, influencer and RISG services.
                </p>
                <p className="terms-highlight">
                    By booking any package, you accept and agree to follow the rules below.
                </p>
            </div>

            <div className="terms-sections">
                {sections.map((section) => (
                    <div
                        key={section.id}
                        className={`terms-section ${openSection === section.id ? 'active' : ''}`}
                    >
                        <div 
                            className="terms-section-header"
                            onClick={() => toggleSection(section.id)}
                        >
                            <h3>{section.title}</h3>
                            {openSection === section.id ? <FaChevronUp /> : <FaChevronDown />}
                        </div>
                        
                        {openSection === section.id && (
                            <div className="terms-section-content">
                                <pre>{section.content}</pre>
                            </div>
                        )}
                    </div>
                ))}
            </div>

            <div className="terms-footer">
                <p>Last Updated: February 2026</p>
                <p>For questions or clarifications, contact: <a href="mailto:1001_nakul@badabuilder.com">1001_nakul@badabuilder.com</a></p>
            </div>
        </div>
    );
};

export default MarketingRules;
